---

name: Open Stella Launcher

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-7, windows-8.1, windows-10, windows-11, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Run Stella Launcher
        run: |
          "./Genshin Stella Mod Launcher.exe"
